features:
  versions:
    - HTTP_VERSION_1
    - HTTP_VERSION_2
  protocols:
    - PROTOCOL_GRPC_WEB
    - PROTOCOL_GRPC
  codecs:
    - CODEC_PROTO
    - CODEC_JSON
  compressions:
    - COMPRESSION_IDENTITY
  stream_types:
    - STREAM_TYPE_UNARY

  supports_trailers: true
  supports_tls: true
  supports_tls_client_certs: false
  supports_h2c: false
  supports_connect_get: false
  supports_message_receive_limit: false
